include(":analyzer-lib"
        , ":analyzer-lib"
        , ":analyzer-cli"
        , ":ascii-lib"
        , ":ascii-encoder-cli"
        , ":ascii-decoder-cli"
        , ":huffman-code-lib"
        , ":huffman-code-encoder-cli"
        , ":huffman-code-decoder-cli"
        , ":arithmetic-coding-lib"
        , ":arithmetic-coding-cli"
        , ":lzw-lib")